# Project name
project_name: safeip

# Build configuration
builds:
  - binary: safeip
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

# Archive configuration
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

# Release configuration
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: safeip
    homepage: https://github.com/darklight147/safeip
    tap:
      owner: darklight147
      name: homebrew-safeip
    commit_author:
      name: darklight147
      email: belkamelmohamed@gmail.com

before:
  hooks:
    - go run main.go completion zsh > completions/goreleaser.zsh
    - go run main.go completion fish > completions/goreleaser.fish
    - go run main.go completion bash > completions/goreleaser.bash

checksum:
  name_template: "checksums.txt"
