# Project name
project_name: safeip

# Build configuration
builds:
  - binary: safeip
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

# Archive configuration
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

# Release configuration
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: safeip
    homepage: https://github.com/darklight147/safeip
    tap:
      owner: darklight147
      name: homebrew-safeip
    commit_author:
      name: darklight147
      email: belkamelmohamed@gmail.com

    # extra_install: |-
    #   bash_completion.install "completions/goreleaser.bash" => "goreleaser"
    #   zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
    #   fish_completion.install "completions/goreleaser.fish"

    description: "safeip is a CLI tool to Mask IP addresses and DNS-Like entries from STDIN or FILE."

before:
  hooks:
    - mkdir completions
    - go run main.go completion zsh >"completions/goreleaser.zsh" && chmod 755 completions/goreleaser.zsh
    - go run main.go completion fish >"completions/goreleaser.fish" && chmod 755 completions/goreleaser.fish
    - go run main.go completion bash >"completions/goreleaser.bash" && chmod 755 completions/goreleaser.bash
    - ls -la completions

checksum:
  name_template: "checksums.txt"
