name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore: # ignore changes to the README.md file
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.21.3

jobs:
  build:
    runs-on: ${{ matrix.os }}

    name: build-${{ matrix.os }}

    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            macos-latest,
            windows-latest,
            [self-hosted, ARM64, macOS],
          ]
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: ${{ env.GO_VERSION }}
          # architecture: ${{ runner.arch }}

      - name: download packages
        run: |
          go mod download
          go mod verify

      - name: Build
        if: ${{ matrix.os != 'windows-latest' }}
        run: go build -o safeip

      - name: Build
        if: ${{ matrix.os == 'windows-latest' }}
        run: go build -o safeip.exe

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: safeip-${{ runner.os }}-${{ runner.arch }}
          path: safeip

      - name: Test if IP is masked ${{ runner.os }}
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          chmod +x safeip
          echo 9.9.9.9 | ./safeip > test-1.txt

          MASK="XXX.XXX.XXX.XXX"


          if grep -q $MASK test-1.txt; then
            echo "test-1 passed"
          else
            echo "test-1 failed"
            exit 1
          fi

      - name: Test if IP is masked ${{ runner.os }}
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $env:MASK = "XXX.XXX.XXX.XXX"

          & ./safeip.exe | Out-File -FilePath test-1.txt

          if (Select-String -Pattern $env:MASK -Path test-1.txt) {
            Write-Host "test-1 passed"
          } else {
            Write-Host "test-1 failed"
            exit 1
          }
