name: Build and Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.21.3

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            macos-latest,
            windows-latest,
            [self-hosted, Linux, arm64],
          ]
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: ${{ env.GO_VERSION }}
          # architecture: ${{ runner.arch }}

      - name: download packages
        run: |
          go mod download
          go mod verify

      - name: Build
        run: go build -o safeip

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: safeip-${{ runner.os }}-${{ runner.arch }}
          path: safeip

  release:
    runs-on: ubuntu-latest

    needs: build

    permissions: write-all

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: safeip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - run: |
          zip -r safeip.zip safeip
        name: Zip Artifacts

      - name: List Artifacts
        run: ls -Rl safeip

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./safeip/safeip.zip
          name: safeip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.${{ github.run_id }}
