name: Release

on:
  push:
    tags:
      - v*

env:
  GO_VERSION: 1.21.3

jobs:
  goreleaser:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          args: release --rm-dist
          version: lastest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
